# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarItem',
            new_name='CartItem',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
