# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatured',
            name='image',
            field=models.ImageField(blank=True, upload_to=product.models.image_upload_to_featured),
        ),
    ]
